"""empty message

Revision ID: 512d75e32baf
Revises: 
Create Date: 2018-10-09 14:48:58.410163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512d75e32baf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.Column('prod_name', sa.String(length=64), nullable=True),
    sa.Column('prod_unit_scale', sa.String(length=32), nullable=True),
    sa.Column('prod_value', sa.Float(), nullable=True),
    sa.Column('prod_reserve', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prod_name')
    )
    op.create_index(op.f('ix_productes_id_produto'), 'productes', ['id_produto'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('situation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_store_name'), 'stores', ['store_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('id_loja', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_loja'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stores_store_name'), table_name='stores')
    op.drop_table('stores')
    op.drop_table('requests')
    op.drop_index(op.f('ix_productes_id_produto'), table_name='productes')
    op.drop_table('productes')
    # ### end Alembic commands ###
