"""empty message

Revision ID: e6e53fb365bb
Revises: 512d75e32baf
Create Date: 2018-10-09 15:21:15.081578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e53fb365bb'
down_revision = '512d75e32baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productes', sa.Column('prod_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productes', 'prod_type')
    # ### end Alembic commands ###
